# Dependabot configuration file:

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "bratanon"
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
